### ISSUE TITLE
iit.js

### ISSUE THREAD

**Issue by fabiovalse** [fabiovalse/campusmap_etl#1]
@andreaderrico2 From one run to another, person IDs may change. This happens when new persons are present on the website. It is necessary to change the person_id variable from an incremental integer to a specific ID taken from the website (e.g., the ID in the href variable should be stable).

**Comment by nitaku** [comment]
The person's email could also be used as an identifier

**Comment by fabiovalse** [comment]
Email should be the right ID for person.

**Comment by fabiovalse** [comment]
@andreaderrico2 The names of the image files that are downloaded should be changed according to new ID format. Example: name.surname@iit.cnr.it
